### ISSUE TITLE
installation broken in MacOS

### ISSUE THREAD

**Issue by arademaker** [guicho271828/cl-sat.glucose#1]
The automation of the installation of the SAT solver is not working and not necessary. I would remove it and make clear to the users that the systems must be in the PATH. Also, I would combine all APIs in the single system cl-sat.

**Comment by guicho271828** [comment]
Id like to know a bit more detail, which API are you referring to?
AFAIK subsystem as a plug-in has been considered successful in systems like CL-DBI (SQL interface) and clack (web server).

**Comment by guicho271828** [comment]
For MacOS specific things that can be easily fixed by `#ifdef` in makefile, I am ready to merge the pull requests.

**Comment by guicho271828** [comment]
1. Regarding the build failure of the solver on Mac, I suppose the Mac specific things can be easily fixed by `#ifdef` in makefile, I am ready to merge such a pull request. I need an error log, which is helpful if I do the fix by myself.
2. Regarding the API, Id like to know a bit more detail, which API are you referring to? AFAIK subsystem as a plug-in has been considered successful in libraries like CL-DBI (SQL interface) and clack (web server). One-big-system approach does not work.

**Comment by guicho271828** [comment]
Update on this: If you want the latest SAT solver from competitions, use the `:competition` option in cl-sat.

**Comment by quicklisp** [comment]
What changed? I get this now: http://report.quicklisp.org/2019-08-06/failure-report/cl-sat.glucose.html#cl-sat.glucose

**Comment by guicho271828** [comment]
The glucose server started using https.

**Comment by guicho271828** [comment]
this is now fixed.
